In [ ]:
************************************************NUMPY NOTES*********************************************************************


NumPy It is an fundamental package which is used for scientfic computation in python It consist of robust data structure which is called multi dimensional array

Numerical Python extensively effecient for efficient mathematical learning It allows user to store large amount of numerical data in the form of array using less memory and perform extensive operation effeciently

Numpy array stores homogeneous numerical data


In [ ]:
Homogeneous like this [3,4,5]
Hetrogenous like this ['hello',2,4]

In [ ]:
import numpy as np


In [ ]:
ar=np.array([1,2,3,34,4,5])
type (ar)

In [ ]:
l=[2222,3,34,4,54,56]
print(l)
ar=np.array([22,3,34,44])
ar

In [ ]:
l=[1,2,3,4]                #in python
for i in range (len(l)):
    l[i]=l[i]+5
print(l)

In [ ]:
l=[1,2,3,4]
ar=np.array([l])
ar=ar+5
print(ar)

In [ ]:
l1=[122222,3,3,3,4]                        #in python 
l2=[333333,5,5,6,6]
print(l1+l2)

In [ ]:
l1=[122222,3,3,3,4]                        # add in numpy 
l2=[333333,5,5,6,6]
ar1=np.array([l1])
ar2=np.array([l2])
ar1+ar2

In [ ]:
True =1  , False=0

In [ ]:
ar=np.array([2.6,9])
ar

In [ ]:
ar=np.array(['sum',2,3,34,4])  # all value show in string 
ar

In [ ]:
"Operation nover 1d array"!

In [ ]:
h=[2,3,43,4,56,67]
ar=np.array(h)
ar

In [ ]:
ar.size       #SIZE OF ARRAY

In [ ]:
ar.shape      #SHAPE OF ARRAY

In [ ]:
len(ar)       #LENGTH OF ARRAY

In [ ]:
BMI(BODY MASS INDEX)
THE FORMULA OF BODY MASS INDEX
BMI=W/(H***2)

In [ ]:
height=[2,3,4,5]
weight=[6,7,8,9]
h=np.array([height])
w=np.array([weight])
bmi=w/(h**2)
bmi

In [ ]:
FIND THE MAXIMUM AND MINIMUM VALUES 

In [ ]:
ar=[222,3,3,34]
max(ar)

In [ ]:
ar=[34,5,6,7777]
min(ar)

In [ ]:
From the given array entract all the element which are greater that "m" and less than "n"
notes -"m" and "n" are integer values proivde as input 

In [ ]:
height=[2,3,4,54]
weight=[3,4,5,6565]
h=np.array([height])
w=np.array([weight])
m=10
n=4444
h[(h>m)&(w<n)]

In [ ]:
ar=np.array([2,3,4,5,6])    # start end and step
ar[1:4:2]

In [ ]:
number=[2,3,4,4,54,5]
price=[234,5,5,666,55,44]
ar1=np.array(number)
ar2=np.array(price)
ar1

In [ ]:
how many iteam sold in table 

In [ ]:
print(ar1.sum())

In [ ]:
what the average price of the product sold by the e commrece company


In [ ]:
print(ar2.mean())

In [ ]:
what the price of the costliest iteam, sold

In [ ]:
print(ar2.max())

In [ ]:
what the total revenue of the company
revenue =price*quantity

In [ ]:
print(ar1*ar2)

In [ ]:
demand for the 3th product on the list higher than that for the 5th product

In [ ]:
print(ar1[2]>ar1[4])

In [ ]:
how amny product fall under the categrary of expensive goods 
an expensive good is one whose price is higher than average price of the product sold by the company

In [ ]:
avg=ar2.mean()
avg

In [ ]:
print(ar2>avg)

In [ ]:
ar2[ar2>avg]

In [ ]:
MUTIDIMENTIONAL ARRAY 


In [3]:
#THIS IS 1D ARRAY                              
import numpy as np
ar=np.array([3,34,45,56])
ar.ndim


1

In [4]:
#This is 2D array
ar=np.array([
    [1,2,3],
    [2,3,4],
    [6,7,8]
])
ar.ndim

2

In [5]:
#this is 3D araay 
ar=np.array([
    [
        [2,3,3],
        [5,5,6],
        [8,9,9]
    ]
])
ar.ndim

3

In [7]:
ar=np.array([                     #first row and columns
    [2,3,4],
    [4,5,6]
    
])
ar.shape

(2, 3)

In [9]:
ar=np.array([
    [2,3,4],
    [5,6,6]
    
])
ar.size

6

In [14]:
ar=np.array([
    [2,3,4],
    [7,5,5]
    
])
ar.itemsize

4

In [ ]:
axis 0= Row
axis 1=columns

In [18]:
ar=np.array([                     #multiply
    [2,3,4],
    [555555555555,6,7]
    
])
ar*2

array([[            4,             6,             8],
       [1111111111110,            12,            14]], dtype=int64)

In [19]:
ar=np.array([
    [2,3,4],                         #divided
    [5,6,7]
    
])
ar/2

array([[1. , 1.5, 2. ],
       [2.5, 3. , 3.5]])

In [21]:
ar=np.array([[1,2],[3,4]])             #2d
ar.ndim

2

In [23]:
ar=np.array([
    [2,2,2],                       #indexing
    [3,3,3],
    [4,4,4]
])
ar[2]

array([4, 4, 4])

In [24]:
ar=np.array([
    [2,2,2],                       #indexing
    [3,3,3],
    [4,4,4]
]) 
ar[1]

array([3, 3, 3])

In [25]:
ar=np.array([
    [2,2,2],                       #indexing
    [3,3,3],
    [4,4,4]
]) 
ar[0]

array([2, 2, 2])

In [26]:
ar=np.array([
    [2,2,2],                       #indexing
    [3,3,3],
    [4,4,4]
]) 
ar[1][0]

3

In [27]:
ar=np.array([
    [2,3,4],                       #indexing
    [6,8,9],
    [2,8,7]
]) 
ar[2][1]

8

In [29]:
ar=np.array([
    [2,2,2,3],                       #indexing
    [3,3,3,65],
    [4,4,4,6]
]) 
ar[:][2]

array([4, 4, 4, 6])

In [30]:
ar=np.array([
    [2,2,2,3],                       #indexing
    [3,3,3,65],
    [4,4,4,6]
]) 
ar[2][:]

array([4, 4, 4, 6])

In [32]:
ar=np.array([
    [11,22,33,44,55],
    [66,77,88,99,00],
    [111,222,333,444,555]
])
ar[1][4]

0

In [36]:
ar=np.array([
    [11,22,33,44,55],
    [66,77,88,99,00],
    [111,222,333,444,555]
])
ar[2][:]

array([111, 222, 333, 444, 555])

In [37]:
ar=np.array([
    [11,22,33,44,55],
    [66,77,88,99,00],
    [111,222,333,444,555]
])
ar[:,4]

array([ 55,   0, 555])

In [ ]:
Intersect1d $ setdiff1d  ?

In [41]:
n1=np.array([2,3,4,6])
n2=np.array([3,4,5,6])               #intersect
np.intersect1d(n1,n2)

array([3, 4, 6])

In [39]:
n1=np.array([2,3,4])                #intersect
n2=np.array([3,4,5])
np.intersect1d(n2,n1)

array([3, 4])

In [42]:
n1=np.array([2,3,4])
n2=np.array([3,4,5])                #setdiff
np.setdiff1d(n1,n2)


array([2])

In [43]:
n1=np.array([2,3,4])                #setdiff
n2=np.array([3,4,5])
np.setdiff1d(n2,n1)

array([5])

In [ ]:
V STACK , H STACK  , COLUMN-STACK  ?
column all the array should be same 

In [ ]:
import numpy as np

In [46]:
n1= np .array([11,22,33,44])            #vstack
n2=np.array([22,33,44,44])
np.vstack((n1,n2))

array([[11, 22, 33, 44],
       [22, 33, 44, 44]])

In [48]:
n1= np .array([11,22,33,44])            #vstack
n2=np.array([22,3,333,4])
np.vstack((n2,n1))

array([[ 22,   3, 333,   4],
       [ 11,  22,  33,  44]])

In [54]:
n1=np.array ([2,3,4])                 #htack
n2=np.array([2,3,5])
np.hstack((n2,n1))

array([2, 3, 5, 2, 3, 4])

In [56]:
n1=np.array ([2,3,4])                 #column_stack
n2=np.array([2,3,5])
np.column_stack((n1,n2))

array([[2, 2],
       [3, 3],
       [4, 5]])

In [57]:
n1=np.array ([2,3,4])                 #column_stack
n2=np.array([2,3,5])
np.column_stack((n2,n1))

array([[2, 2],
       [3, 3],
       [5, 4]])

In [ ]:
ARANGE ,   FULL   ,  RANDOM RADINT  ?

In [ ]:
import numpy as np

In [65]:
np.arange(2,50,2)           #range start,end , step


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [66]:
n1=np.full((3,4),10)
n1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [67]:
n1=np.full((3,7),10)
n1

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [69]:
n1=np.full((9,4),10)
n1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
Equal ,ONES, ZEROES,LINSPACE,TITLE  ?

In [70]:
n1=np.array([2,3,4])        #f n1 or n2 equal or not ouput (True or false)
n2=np.array([4,5,6])
np.equal(n1,n2)

array([False, False, False])

In [72]:
ar=np.ones((2,3,3))     # dimension ,start ,end
ar

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
ar=np.ones((1,3,4))
ar

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [77]:
ar=np.ones((2,3,6))
ar

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [79]:
ar=np.zeros((2,3))        #row and columns
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
ar=np.zeros((3,3))
ar

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
ar=np.linspace(1,10,54)         
ar

array([ 1.        ,  1.16981132,  1.33962264,  1.50943396,  1.67924528,
        1.8490566 ,  2.01886792,  2.18867925,  2.35849057,  2.52830189,
        2.69811321,  2.86792453,  3.03773585,  3.20754717,  3.37735849,
        3.54716981,  3.71698113,  3.88679245,  4.05660377,  4.22641509,
        4.39622642,  4.56603774,  4.73584906,  4.90566038,  5.0754717 ,
        5.24528302,  5.41509434,  5.58490566,  5.75471698,  5.9245283 ,
        6.09433962,  6.26415094,  6.43396226,  6.60377358,  6.77358491,
        6.94339623,  7.11320755,  7.28301887,  7.45283019,  7.62264151,
        7.79245283,  7.96226415,  8.13207547,  8.30188679,  8.47169811,
        8.64150943,  8.81132075,  8.98113208,  9.1509434 ,  9.32075472,
        9.49056604,  9.66037736,  9.83018868, 10.        ])

In [86]:

import numpy as np
ar=np.array([2,3])
np.title(ar,2)


AttributeError: module 'numpy' has no attribute 'title'

In [ ]:
EYE FUNCTION RETURN IDENTITY MATRICS FOR THE GIVEN ROW AND COLUMNS

In [87]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [90]:
np.eye(3,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])